### ISSUE TITLE
FakeRedis does not have a close method

### ISSUE THREAD

**Issue by pawel-lmcb** [jamesls/fakeredis#159]
Settings this up for the testing environment in my django app, I get the following:
(in settings.py)
  CACHES = {
    "default": {
      "BACKEND" : "fakeredis.FakeRedis",
      "OPTIONS": {
        "REDIS_CLIENT_CLASS": "fakeredis.FakeRedis",
      }
    }
  }

Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/Users/<removed>/Development/<removed>/aws/tests.py", line 81, in test_aws_credentials_retry
    response = self.client.post('<removed>', data=data)
  File "/usr/local/lib/python2.7/site-packages/django/test/client.py", line 541, in post
    secure=secure, **extra)
  File "/usr/local/lib/python2.7/site-packages/django/test/client.py", line 343, in post
    secure=secure, **extra)
  File "/usr/local/lib/python2.7/site-packages/django/test/client.py", line 409, in generic
    return self.request(**r)
  File "/usr/local/lib/python2.7/site-packages/django/test/client.py", line 476, in request
    response = self.handler(environ)
  File "/usr/local/lib/python2.7/site-packages/django/test/client.py", line 158, in __call__
    response.close()                    # will fire request_finished
  File "/usr/local/lib/python2.7/site-packages/django/http/response.py", line 254, in close
    signals.request_finished.send(sender=self._handler_class)
  File "/usr/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 191, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/lib/python2.7/site-packages/django/core/cache/__init__.py", line 123, in close_caches
    cache.close()
AttributeError: 'FakeRedis' object has no attribute 'close'

Adding in close method to fakeredis.py like below solves this for me

def close():
  pass

However I don't want to fork, and in case I am doing something wrong wanted to raise this here.

**Comment by bmerry** [comment]
redis.Redis doesn't have a close method either, so I don't think this is a bug in fakeredis.
