### ISSUE TITLE
compatibility error with 1.0 release?

### ISSUE THREAD

**Issue by kapilt** [jamesls/fakeredis#233]
we've been using fake redis with our unit tests, post the publishing of the 1.0 release a few hours ago our ci tests started returning failures

```
2019-01-24T11:28:53.5373154Z =================================== FAILURES ===================================
2019-01-24T11:28:53.5373831Z ________ EmailTest.test_email_to_email_message_map_without_ldap_manager ________
2019-01-24T11:28:53.5376815Z [gw0] linux2 -- Python 2.7.15 /home/vsts/work/1/s/.tox/py27-cov/bin/python
2019-01-24T11:28:53.5376956Z Traceback (most recent call last):
2019-01-24T11:28:53.5377026Z   File "/home/vsts/work/1/s/tools/c7n_mailer/tests/test_email.py", line 53, in setUp
2019-01-24T11:28:53.5377081Z     self.email_delivery = MockEmailDelivery(MAILER_CONFIG, self.aws_session, logger)
2019-01-24T11:28:53.5377156Z   File "/home/vsts/work/1/s/tools/c7n_mailer/c7n_mailer/email_delivery.py", line 78, in __init__
2019-01-24T11:28:53.5377208Z     self.ldap_lookup = self.get_ldap_connection()
2019-01-24T11:28:53.5377279Z   File "/home/vsts/work/1/s/tools/c7n_mailer/tests/test_email.py", line 46, in get_ldap_connection
2019-01-24T11:28:53.5377511Z     return get_ldap_lookup(cache_engine='redis')
2019-01-24T11:28:53.5377577Z   File "/home/vsts/work/1/s/tools/c7n_mailer/tests/common.py", line 359, in get_ldap_lookup
2019-01-24T11:28:53.5377804Z     ldap_lookup.caching.set('michael_bolton', michael_bolton)
2019-01-24T11:28:53.5377860Z   File "/home/vsts/work/1/s/tools/c7n_mailer/c7n_mailer/ldap_lookup.py", line 205, in set
2019-01-24T11:28:53.5377929Z     return self.connection.set(key, json.dumps(value))
2019-01-24T11:28:53.5378348Z   File "/home/vsts/work/1/s/.tox/py27-cov/lib/python2.7/site-packages/redis/client.py", line 1394, in set
2019-01-24T11:28:53.5378576Z     return self.execute_command('SET', *pieces)
2019-01-24T11:28:53.5378834Z   File "/home/vsts/work/1/s/.tox/py27-cov/lib/python2.7/site-packages/redis/client.py", line 754, in execute_command
2019-01-24T11:28:53.5378890Z     connection.send_command(*args)
2019-01-24T11:28:53.5379312Z   File "/home/vsts/work/1/s/.tox/py27-cov/lib/python2.7/site-packages/redis/connection.py", line 619, in send_command
2019-01-24T11:28:53.5379370Z     self.send_packed_command(self.pack_command(*args))
2019-01-24T11:28:53.5380023Z   File "/home/vsts/work/1/s/.tox/py27-cov/lib/python2.7/site-packages/redis/connection.py", line 615, in send_packed_command
2019-01-24T11:28:53.5380372Z     raise e
2019-01-24T11:28:53.5380664Z AttributeError: 'module' object has no attribute 'ensure_binary'
```

what version of redis client is fakeredis 1.0 intended to work with ?

**Comment by bmerry** [comment]
What version of `six` are you using?

**Comment by kapilt** [comment]
looks like we're on six == 1.11.0

**Comment by bmerry** [comment]
That'll be the problem. fakeredis 1.0 [requires](https://github.com/jamesls/fakeredis/blob/1.0/setup.py#L31) `>=1.12`.

**Comment by kapilt** [comment]
thanks for the info, its odd that the pip install didn't fail, it looks like that dep is properly declared in fakeredis pkg metadata, i would have expected a conflict requirements message.

**Comment by tony** [comment]
First, thanks for the great project! Sorry if this is a distraction. I spent some time figuring out why this was happening (due to something unrelated, Pipfile.lock stuff).

I still have a bit of a request :laughing: :

@bmerry @kapilt It may be worth investigating a compat module fix for ensure_binary. This is breaking on my python 3.7 and it's not obvious where it's coming from.

There are other packages I'm using that pull in six, sometimes I have 1.12.0 (currently do now), but it's easy for this to get masked behind conditional pip package pins in a project's dependencies.

If possible, consider vendorizing `ensure_binary` instead of using six, if it's the only thing that has a version requirement.

Six is also a pretty heavy dependency.

http://lucumr.pocoo.org/2013/5/21/porting-to-python-3-redux/

**Comment by tony** [comment]
Due to this I'm actually using an older fakeredis version for now.  

To repeat: I don't believe fakeredis has anything wrong with it - it's just on a big project it's easy for other packages to mask this. 

Though, if using `six` can be avoided - it may help users downstream

From libconda, license BSD:

```python
def ensure_binary(value):
    return value.encode('utf-8') if hasattr(value, 'encode') else value
```

https://github.com/conda/libconda/blob/28d77a7506f76cbf537c1f0ddc947384cab15415/libconda/compat.py#L104
