### ISSUE TITLE
Failing to migrate to v1.0 on django project

### ISSUE THREAD

**Issue by belugame** [jamesls/fakeredis#234]
This is on a django 1.11 / python 2.7 project. (also django-redis==4.10.0, redis==2.10.6)
I can't work out how to migrate my settings to be compatible with version 1.0. Or is the setup contradictory to what 1.0 needs?

This is how it worked with the <1.0:

```
In [1]: settings.CACHES
Out[1]: 
{'admin': {'BACKEND': 'django_redis.cache.RedisCache',
  'KEY_PREFIX': 'admin',
  'LOCATION': 'redis://redis:6379/3',
  'OPTIONS': {'CLIENT_CLASS': 'django_redis.client.DefaultClient',
   'REDIS_CLIENT_CLASS': 'fakeredis.FakeStrictRedis'}},
 'default': {'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
  'LOCATION': 'foobar'},
 'sessions': {'BACKEND': 'django_redis.cache.RedisCache',
  'KEY_PREFIX': 'shop-sessions',
  'LOCATION': 'redis://redis:6379/2',
  'OPTIONS': {'CLIENT_CLASS': 'django_redis.client.DefaultClient',
   'REDIS_CLIENT_CLASS': 'fakeredis.FakeStrictRedis'}}}
```

With v1.0 I receive this on pretty much all my tests:

```
======================================================================
ERROR: test_something (foobar.messaging.tests.test_ticket_views.ViewsSupportingCORSTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/shop/current/app/django-sites/foobar/utils/testcases.py", line 603, in tearDown
    self.client.logout()
  File "/var/venv-stable/lib/python2.7/site-packages/django/test/client.py", line 685, in logout
    if self.session:
  File "/var/venv-stable/lib/python2.7/site-packages/django/test/client.py", line 459, in session
    session.save()
  File "/var/venv-stable/lib/python2.7/site-packages/django/contrib/sessions/backends/cache.py", line 57, in save
    return self.create()
  File "/var/venv-stable/lib/python2.7/site-packages/django/contrib/sessions/backends/cache.py", line 44, in create
    self._session_key = self._get_new_session_key()
  File "/var/venv-stable/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 164, in _get_new_session_key
    if not self.exists(session_key):
  File "/var/venv-stable/lib/python2.7/site-packages/django/contrib/sessions/backends/cache.py", line 71, in exists
    return session_key and (self.cache_key_prefix + session_key) in self._cache
  File "/var/venv-stable/lib/python2.7/site-packages/django/core/cache/backends/base.py", line 203, in __contains__
    return self.has_key(key)
  File "/var/venv-stable/lib/python2.7/site-packages/django_redis/cache.py", line 39, in _decorator
    raise e.parent
ConnectionError: Error -2 connecting to redis:6379. Name or service not known.

```

It appears to be looking for the "real" redis server still. 
If I change REDIS_CLIENT_CLASS to CLIENT_CLASS I get:

```
    self.client.logout()
  File "/var/venv-stable/lib/python2.7/site-packages/django/test/client.py", line 685, in logout
    if self.session:
  File "/var/venv-stable/lib/python2.7/site-packages/django/test/client.py", line 459, in session
    session.save()
  File "/var/venv-stable/lib/python2.7/site-packages/django/contrib/sessions/backends/cache.py", line 57, in save
    return self.create()
  File "/var/venv-stable/lib/python2.7/site-packages/django/contrib/sessions/backends/cache.py", line 44, in create
    self._session_key = self._get_new_session_key()
  File "/var/venv-stable/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py", line 164, in _get_new_session_key
    if not self.exists(session_key):
  File "/var/venv-stable/lib/python2.7/site-packages/django/contrib/sessions/backends/cache.py", line 71, in exists
    return session_key and (self.cache_key_prefix + session_key) in self._cache
  File "/var/venv-stable/lib/python2.7/site-packages/django/core/cache/backends/base.py", line 203, in __contains__
    return self.has_key(key)
  File "/var/venv-stable/lib/python2.7/site-packages/django_redis/cache.py", line 32, in _decorator
    return method(self, *args, **kwargs)
  File "/var/venv-stable/lib/python2.7/site-packages/django_redis/cache.py", line 124, in has_key
    return self.client.has_key(*args, **kwargs)
AttributeError: 'FakeStrictRedis' object has no attribute 'has_key'


```

**Comment by bmerry** [comment]
I don't use Django myself, but from looking at the code in django-redis, I think this is happening because it is constructing the FakeStrictRedis with a real redis ConnectionPool, which then overrides any fakery from fakeredis. I think what *might* work (from inspecting the code, but totally untested) is to remove `REDIS_CLIENT_CLASS`, and instead specify
```python
CONNECTION_POOL_KWARGS=dict(
    connection_class=fakeredis.FakeConnection,
    server=fakeredis.FakeServer()
)
```
which will cause django-redis to construct the connection pool with fake connections. If this gets specified in more than one place, then you probably want to construct the `fakeredis.FakeServer` first and pass in a reference to it each time so that they share the same simulated redis server.

**Comment by belugame** [comment]
Thank you very much for looking into it. I have tried using this inside my CACHES setting. But it has not changed the outcome :(

**Comment by bmerry** [comment]
I'm afraid there's not a lot more I can do since I don't know anything about Django. Maybe try asking the django-redis people and pointing them at this ticket.

**Comment by sarendsen** [comment]
@belugame It's without pooling but i created a custom ConnectionFactory for this issue. Though fake pooling should be possible to implement trough the factory aswell.

```
from django_redis.pool import ConnectionFactory as DjangoRedisConnectionFactory

class ConnectionFactory(DjangoRedisConnectionFactory):
    def get_connection(self, params):
        return self.redis_client_cls(**self.redis_client_cls_kwargs)
```

And my settings

```
DJANGO_REDIS_CONNECTION_FACTORY = "core.pool.ConnectionFactory"

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://localhost:6379/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "REDIS_CLIENT_CLASS": "fakeredis.FakeStrictRedis",
        },
    }
}
```

**Comment by belugame** [comment]
Thank you very much, @sarendsen. 99% of the test suite is passing now :)
