### ISSUE TITLE
AttributeError: 'FakeConnection' object has no attribute 'health_check_interval'

### ISSUE THREAD

**Issue by vii** [jamesls/fakeredis#245]
fakeredis==1.0.3
redis==3.3.4
hiredis==1.0.0

```
>>> import fakeredis
>>> r = fakeredis.FakeStrictRedis()
>>> r.set('foo', 'bar')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/srv/venvs/service/trusty/service_venv_python3.6/lib/python3.6/site-packages/redis/client.py", line 1519, in set
    return self.execute_command('SET', *pieces)
  File "/srv/venvs/service/trusty/service_venv_python3.6/lib/python3.6/site-packages/redis/client.py", line 838, in execute_command
    conn.send_command(*args)
  File "/srv/venvs/service/trusty/service_venv_python3.6/lib/python3.6/site-packages/redis/connection.py", line 674, in send_command
    check_health=kwargs.get('check_health', True))
  File "/srv/venvs/service/trusty/service_venv_python3.6/lib/python3.6/site-packages/redis/connection.py", line 648, in send_packed_command
    self.check_health()
  File "/srv/venvs/service/trusty/service_venv_python3.6/lib/python3.6/site-packages/redis/connection.py", line 629, in check_health
    if self.health_check_interval and time() > self.next_health_check:
AttributeError: 'FakeConnection' object has no attribute 'health_check_interval'
```

**Comment by vii** [comment]
this is fine with redis=3.2.1 ...

**Comment by Raab70** [comment]
Duplicate of #240 fixed in #243

**Comment by MetcalfeTom** [comment]
Would you mind tagging a new release with this? 🙏We use your awesome package as part of our test suite and this issue is preventing us from upgrading from a vulnerable version of `redis`

**Comment by bmerry** [comment]
> Would you mind tagging a new release with this?

Done (1.0.4).
