### ISSUE TITLE
Can't use lock

### ISSUE THREAD

**Issue by davidt99** [jamesls/fakeredis#259]
Using redis lock raises an error:
```python
>>> redis = fakeredis.FakeRedis()
>>> lock = redis.lock('asd', 12*60*60)
>>> with lock:
...     print('')
... 

Traceback (most recent call last):
  File ".venv/lib/python3.6/site-packages/fakeredis/_server.py", line 2361, in evalsha
    script = self._server.script_cache[sha1]
KeyError: b'c3f8721cbb97f72bc19e972846bd7aaf91901658'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".venv/lib/python3.6/site-packages/redis/client.py", line 3575, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File ".venv/lib/python3.6/site-packages/redis/client.py", line 2761, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File ".venv/lib/python3.6/site-packages/redis/client.py", line 775, in execute_command
    return self.parse_response(connection, command_name, **options)
  File ".venv/lib/python3.6/site-packages/redis/client.py", line 789, in parse_response
    response = connection.read_response()
  File ".venv/lib/python3.6/site-packages/fakeredis/_server.py", line 2565, in read_response
    raise response
  File ".venv/lib/python3.6/site-packages/fakeredis/_server.py", line 715, in _run_command
    result = func(*args)
  File ".venv/lib/python3.6/site-packages/fakeredis/_server.py", line 2363, in evalsha
    raise redis.exceptions.NoScriptError(NO_MATCHING_SCRIPT_MSG)
redis.exceptions.NoScriptError: No matching script. Please use EVAL.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File ".venv/lib/python3.6/site-packages/redis/lock.py", line 150, in __exit__
    self.release()
  File ".venv/lib/python3.6/site-packages/redis/lock.py", line 226, in release
    self.do_release(expected_token)
  File ".venv/lib/python3.6/site-packages/redis/lock.py", line 231, in do_release
    client=self.redis)):
  File ".venv/lib/python3.6/site-packages/redis/client.py", line 3581, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File ".venv/lib/python3.6/site-packages/redis/client.py", line 2761, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File ".venv/lib/python3.6/site-packages/redis/client.py", line 774, in execute_command
    connection.send_command(*args)
  File ".venv/lib/python3.6/site-packages/redis/connection.py", line 620, in send_command
    self.send_packed_command(self.pack_command(*args))
  File ".venv/lib/python3.6/site-packages/redis/connection.py", line 600, in send_packed_command
    self._sock.sendall(item)
  File ".venv/lib/python3.6/site-packages/fakeredis/_server.py", line 778, in sendall
    self._parser.send(data)
  File ".venv/lib/python3.6/site-packages/fakeredis/_server.py", line 699, in _parse_commands
    self._process_command(fields)
  File ".venv/lib/python3.6/site-packages/fakeredis/_server.py", line 797, in _process_command
    result = self._run_command(func, sig, fields[1:], False)
  File ".venv/lib/python3.6/site-packages/fakeredis/_server.py", line 715, in _run_command
    result = func(*args)
  File ".venv/lib/python3.6/site-packages/fakeredis/_server.py", line 2364, in evalsha
    return self.eval(script, numkeys, *keys_and_args)
  File ".venv/lib/python3.6/site-packages/fakeredis/_server.py", line 2317, in eval
    from lupa import LuaRuntime, LuaError
ModuleNotFoundError: No module named 'lupa'
```

**Comment by bmerry** [comment]
As mentioned in the README, Lua support requires lupa to be installed. While you're not using Lua directly, `Redis.lock` is implemented in Lua.

**Comment by davidt99** [comment]
Installing lupa fixed it, thanks!
I was upgrading from 0.x, I would add that note in the porting notes.
