### ISSUE TITLE
Broken with redis-py 3.4.0

### ISSUE THREAD

**Issue by adamchainz** [jamesls/fakeredis#260]
Running the example with redis-py 3.4.0 reveals the breakage:

```
$ cat test.py
import fakeredis
r = fakeredis.FakeStrictRedis()
assert r.set('foo', 'bar') is True
assert r.get('foo') == 'bar'
$ python test.py
Traceback (most recent call last):
  File "/.../python3.8/site-packages/redis/connection.py", line 550, in connect
    sock = self._connect()
  File "/.../python3.8/site-packages/redis/connection.py", line 892, in _connect
    sock.connect(self.path)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    assert r.set('foo', 'bar') is True
  File "/.../python3.8/site-packages/redis/client.py", line 1772, in set
    return self.execute_command('SET', *pieces)
  File "/.../python3.8/site-packages/redis/client.py", line 881, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/.../python3.8/site-packages/redis/connection.py", line 1178, in get_connection
    connection.connect()
  File "/.../python3.8/site-packages/redis/connection.py", line 555, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 2 connecting to unix socket: utf-8. No such file or directory.
```

It seems the `encoding` argument is being intrepreted as `path` now. This is not documented on the upstream changelog: https://github.com/andymccurdy/redis-py/blob/master/CHANGES

**Comment by bmerry** [comment]
Yuck. I've filed andymccurdy/redis-py#1276, and for now I'll work around it by passing the arguments by name rather than position.

**Comment by bmerry** [comment]
I hope to have a fix out early next week. I've made the fixes, but got distracted by trying to test on Python 3.8 which has opened a huge can of worms that I'll put to one side for later.

**Comment by adamchainz** [comment]
Fair, thank you!
