### ISSUE TITLE
TypeError: '<=' not supported between instances of 'NoneType' and 'int', when using run_in_thread sleep_time=None

### ISSUE THREAD

**Issue by graingert** [jamesls/fakeredis#274]
when using:

```
import fakeredis


def main():
    redis = fakeredis.FakeStrictRedis()
    redis_pubsub = redis.pubsub()
    redis_pubsub.subscribe(my_channel=lambda: None)
    return redis_pubsub.run_in_thread(sleep_time=None)


if __name__ == "__main__":
    main()
```

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>>>     self.run()
  File "/home/graingert/.virtualenvs/fr-demo/lib/python3.8/site-packages/redis/client.py", line 2598, in run
    pubsub.get_message(ignore_subscribe_messages=True,
  File "/home/graingert/.virtualenvs/fr-demo/lib/python3.8/site-packages/redis/client.py", line 2513, in get_message
    response = self.parse_response(block=False, timeout=timeout)
  File "/home/graingert/.virtualenvs/fr-demo/lib/python3.8/site-packages/redis/client.py", line 2428, in parse_response
    if not block and not connection.can_read(timeout=timeout):
  File "/home/graingert/.virtualenvs/fr-demo/lib/python3.8/site-packages/fakeredis/_server.py", line 2549, in can_read
    return self._selector.check_can_read(timeout)
  File "/home/graingert/.virtualenvs/fr-demo/lib/python3.8/site-packages/fakeredis/_server.py", line 2474, in check_can_read
    if timeout <= 0:
TypeError: '<=' not supported between instances of 'NoneType' and 'int'

KeyboardInterrupt
```

**Comment by graingert** [comment]
when using, redis==2.10.6, fakeredis==1.1.1

**Comment by graingert** [comment]
see also: https://github.com/andymccurdy/redis-py/issues/821
