### ISSUE TITLE
Unicode errors in set()

### ISSUE THREAD

**Issue by domenkozar** [jamesls/fakeredis#91]
```
feeds/cache.py:128: in store_feed_content
    self.redis_client.set(feed_key, raw_content)
.tox/py27/lib/python2.7/site-packages/fakeredis.py:386: in set
    self._db[name] = to_bytes(value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

x = '<feedán/>', charset = 'ascii', errors = 'strict'

    def to_bytes(x, charset=sys.getdefaultencoding(), errors='strict'):
        if x is None:
            return None
        if isinstance(x, (bytes, bytearray, buffer)) or hasattr(x, '__str__'):
>           return bytes(x)
E           UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 5: ordinal not in range(128)
```

**Comment by danielgoncalves** [comment]
Indeed. When you use set using **redis-py**:

```python
>>> import fakeredis
>>> r = fakeredis.FakeStrictRedis()
>>> r.set('something', u'Alçapão')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/daniel/.virtualenvs/ibpt/local/lib/python2.7/site-packages/fakeredis.py", line 386, in set
    self._db[name] = to_bytes(value)
  File "/home/daniel/.virtualenvs/ibpt/local/lib/python2.7/site-packages/fakeredis.py", line 31, in to_bytes
    return bytes(x)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 2: ordinal not in range(128)
```

Using **redis-py**:

```python
>>> import redis
>>> r = redis.StrictRedis()
>>> r.set('something', u'Alçapão')
True
```

**Comment by vrcmarcos** [comment]
I'm facing this problem right now. Any solution?

**Comment by TereFDS** [comment]
@domenkozar  @vrcmarcos This problem happens if you are using Python 2.x. With Python 3 this error doesn't occur (it is because in python3, strings are encoded in UTF8 by default. By the way, I'll propose a fix for this bug in Python 2

**Comment by faustow** [comment]
To @vrcmarcos and anyone still facing this:
A (_wildly unpopular and even potentially dangerous_) workaround to get this working is to force the  encoding to UTF-8 with `setdefaultencoding`. This method is removed from `sys` after the module is loaded so you need the following hack to make it work: 
```
    import sys
    reload(sys)
    sys.setdefaultencoding('UTF8')
```
Again this is normally discouraged by the core community, but if you know what you're doing go ahead. Also, since this is fakeredis, you're probably running this in a test-mode of your application, so you can use the above only when testing and you should be fine for most cases.
